BookPublishers/Controllers/PublishersController.cs
using BookPublishers.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace BookPublishers.Controllers
{
    [Authorize]
    public class PublishersController : Controller
    {
        PublisherDbContext db = new PublisherDbContext();
        // GET: Qualifications
        public ActionResult Index()
        {
            return View(db.Publishers.Include(b => b.Editors).ToList());
        }
        public ActionResult Create()
        {

            return View();
        }
        public PartialViewResult CreatePublisher()
        {
            return PartialView("_CreatePublisher");
        }
        [HttpPost]
        public PartialViewResult CreatePublisher(Publisher p)
        {
            Thread.Sleep(4000);

            if (ModelState.IsValid)
            {
                db.Publishers.Add(p);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditPublisher(int id)
        {
            var q = db.Publishers.First(x => x.PublisherId == id);
            return PartialView("_EditPublisher", q);
        }
        [HttpPost]
        public PartialViewResult EditPublisher(Publisher t)
        {
            Thread.Sleep(2000);
            if (ModelState.IsValid)
            {
                db.Entry(t).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Publishers.First(x => x.PublisherId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DoDelete(int id)
        {
            Publisher p = new Publisher { PublisherId = id };
            db.Entry(p).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BookPublishers/Views/Publishers/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <button id="spinner" class="btn btn-primary" type="button" style="display:none">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>
    </div>
    <div class="col-12">
        <h3>Add new Publishers</h3>
        @Html.Action("CreatePublisher")
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />

}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
    </script>
    <script>
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
}

BookPublishers/Views/Publishers/Delete.cshtml
@model BookPublishers.Models.Publisher
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3>Confirm Delete</h3>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.publisherName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.publisherName, new { @class = "form-control form-control-sm" })

        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.stablishedDate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.stablishedDate, new { @class = "form-control form-control-sm" })

        </div>
    </div>
    
    <div class="form-group row mb-1">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.PublisherId)

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
        }
    </div>
</div>

BookPublishers/Views/Publishers/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <button id="spinner" class="btn btn-primary" type="button" style="display:none">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>
    </div>
    <div class="col-12">
        <h3>Edit Publishers</h3>
        @Html.Action("EditPublisher", new { id = ViewBag.Id })
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
    </script>
}

BookPublishers/Views/Publishers/Index.cshtml
@model IEnumerable<BookPublishers.Models.Publisher>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Publishers</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add new", "Create", "Publishers", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.publisherName)</th>
                    <th>@Html.DisplayNameFor(x => x.stablishedDate)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var t in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => t.publisherName)</td>
                        <td>@Html.DisplayFor(x => t.stablishedDate)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Publishers", new { id = t.PublisherId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Publishers", new {id=t.PublisherId})" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BookPublishers/Views/Publishers/_CreatePublisher.cshtml
@model BookPublishers.Models.Publisher
@using (Ajax.BeginForm("CreatePublisher", "Publishers", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    OnSuccess = "onSuccess",
    LoadingElementId = "spinner"
}))
{
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.publisherName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.publisherName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.publisherName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.stablishedDate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.stablishedDate, new { @class = "form-control form-control-sm date" })
            @Html.ValidationMessageFor(x => x.stablishedDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

BookPublishers/Views/Publishers/_EditPublisher.cshtml
@model BookPublishers.Models.Publisher
@using (Ajax.BeginForm("EditPublisher", "Publishers", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    OnSuccess = "onSuccess",
    LoadingElementId = "spinner"
}))
{
    @Html.HiddenFor(x => x.PublisherId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.publisherName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.publisherName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.publisherName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.stablishedDate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.stablishedDate, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.stablishedDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}