BookPublishers/Controllers/EditorsController.cs
using BookPublishers.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace BookPublishers.Controllers
{
    [Authorize]
    public class EditorsController : Controller
    {
        PublisherDbContext db = new PublisherDbContext();

        public ActionResult Index()
        {
            return View(db.Editors.Include(x => x.Publisher).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateEditor()
        {
            ViewBag.Publisher = db.Publishers.ToList();
            return PartialView("_CreateEditor");
        }
        [HttpPost]
        public PartialViewResult CreateEditor(Editor f)
        {
            Thread.Sleep(3000);

            if (ModelState.IsValid)
            {
                db.Editors.Add(f);
                db.SaveChanges();
                return PartialView("_Success");
            }
            ViewBag.Publisher = db.Publishers.ToList();
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditEditor(int id)
        {
            ViewBag.Publisher = db.Publishers.ToList();
            var p = db.Editors.First(x => x.EditorId == id);
            return PartialView("_EditEditor", p);
        }
        [HttpPost]
        public PartialViewResult EditEditor(Editor f)
        {
            Thread.Sleep(3000);
            if (ModelState.IsValid)
            {
                db.Entry(f).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            ViewBag.Publisher = db.Publishers.ToList();
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Editors.First(x => x.EditorId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DoDelete(int id)
        {
            Editor t = new Editor { EditorId = id };
            db.Entry(t).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BookPublishers/Views/Editors/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <button id="spinner" class="btn btn-primary" type="button" style="display:none">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>
    </div>
    <div class="col-12">
        <h3>Add new Editors</h3>
        @Html.Action("CreateEditor")
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
    </script>
}

BookPublishers/Views/Editors/Delete.cshtml
@model BookPublishers.Models.Editor
@{
    ViewBag.Title = "Delete";
}
<div class="row">
    <div class="col-12">
        <h3>Confirm Delete</h3>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.EditorName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.EditorName, new { @class = "form-control form-control-sm" })

        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.MobileNo, new { @class = "form-control form-control-sm" })

        </div>
    </div>
    <div class="form-group row mb-1">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.EditorId)

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
        }
    </div>
</div>

BookPublishers/Views/Editors/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <button id="spinner" class="btn btn-primary" type="button" style="display:none">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>
    </div>
    <div class="col-12">
        <h3>Edit Editors</h3>
        @Html.Action("EditEditor", new { id = ViewBag.Id })
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
    </script>
}

BookPublishers/Views/Editors/Index.cshtml
@model IEnumerable<BookPublishers.Models.Editor>
@{ ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h2>Editors</h2>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add new", "Create", "Editors", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.EditorName)</th>
                    <th>@Html.DisplayNameFor(x => x.MobileNo)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var t in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => t.EditorName)</td>
                        <td>@Html.DisplayFor(x => t.MobileNo)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Editors", new { id = t.EditorId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Editors", new {id=t.EditorId })" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BookPublishers/Views/Editors/_CreateEditor.cshtml
@model BookPublishers.Models.Editor
@using (Ajax.BeginForm("CreateEditor", "Editors", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    OnSuccess = "onSuccess",
    LoadingElementId = "spinner"
}, new { id = "f" }))
{
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Publisher, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.PublisherId, new SelectList(ViewBag.Publisher, "PublisherId", "publisherName"), "Select", new { @class = "form-select form-select-sm" })
            @Html.ValidationMessageFor(x => x.PublisherId, "", new { @class = "text-danger" })
        </div>
    </div>
   
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.EditorName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.EditorName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.EditorName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.MobileNo, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

BookPublishers/Views/Editors/_EditEditor.cshtml
@model BookPublishers.Models.Editor
@using (Ajax.BeginForm("EditEditor", "Editors", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    OnSuccess = "onSuccess",
    LoadingElementId = "spinner"
}, new { id = "f" }))
{
    @Html.HiddenFor(x => x.EditorId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Publisher, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.PublisherId, new SelectList(ViewBag.Publisher, "PublisherId", "publisherName"), "Select", new { @class = "form-select form-select-sm" })
            @Html.ValidationMessageFor(x => x.PublisherId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.EditorName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.EditorName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.EditorName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.MobileNo, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}