BookPublishers/Controllers/AuthorsController.cs
using BookPublishers.Models;
using BookPublishers.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookPublishers.Controllers
{
    [Authorize]
    public class AuthorsController : Controller
    {
        // GET: Authors

        PublisherDbContext db = new PublisherDbContext();

        public ActionResult Index()
        {
            return View(db.Authors.Include(x => x.Book).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.Book = db.Books.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(AuthorInputModel t)
        {
            if (ModelState.IsValid)
            {
                var a = new Author
                {
                    AuthorName = t.AuthorName,
                    MobileNo = t.MobileNo,
                    BookId = t.BookId
                };
                string ext = Path.GetExtension(t.picture.FileName);
                string f = Guid.NewGuid() + ext;
                t.picture.SaveAs(Server.MapPath("~/Assets/") + f);
                a.picture = f;
                db.Authors.Add(a);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Book = db.Books.ToList();
            return View(t);
        }
        public ActionResult Edit(int id)
        {
            var e = db.Authors.First(x => x.AuthorId == id);
            ViewBag.Book = db.Books.ToList();
            ViewBag.CurrentPic = e.picture;
            return View(new AuthorEditModel { AuthorId = e.AuthorId, AuthorName = e.AuthorName, MobileNo = e.MobileNo, BookId = e.BookId });
        }
        [HttpPost]
        public ActionResult Edit(AuthorEditModel e)
        {
            var t = db.Authors.First(x => x.AuthorId == e.AuthorId);
            if (ModelState.IsValid)
            {
                t.AuthorName = e.AuthorName;
                t.MobileNo = e.MobileNo;
                t.BookId = e.BookId;
                if (e.picture != null)
                {
                    string ext = Path.GetExtension(e.picture.FileName);
                    string f = Guid.NewGuid() + ext;
                    e.picture.SaveAs(Server.MapPath("~/Assets/") + f);
                    t.picture = f;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Book = db.Books.ToList();
            ViewBag.CurrentPic = t.picture;
            return View(e);
        }
        public ActionResult Delete(int id)
        {
            return View(db.Authors.Include(x => x.Book).First(x => x.AuthorId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DoDelete(int id)
        {
            Author e = new Author { AuthorId = id };
            db.Entry(e).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BookPublishers/Views/Authors/Create.cshtml
@model BookPublishers.ViewModel.AuthorInputModel
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-12">
        <h3>Add new author</h3>
        @using (Html.BeginForm("Create", "Authors", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.AuthorName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.AuthorName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.AuthorName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.MobileNo, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.MobileNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.picture, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.picture, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BookId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.BookId, new SelectList(ViewBag.Book, "BookId", "bookName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.BookId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to list", "Index")
</div>
@section styles{

    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
}

BookPublishers/Views/Authors/Delete.cshtml
@model BookPublishers.Models.Author
@{
    ViewBag.Title = "Delete";
}
<div class="row">
    <div class="col-12">
        <h3>Confirm Delete</h3>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.AuthorName, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.AuthorName)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.MobileNo)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.picture, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-1">
                <img src="~/Assets/@Model.picture" class="img-thumbnail" style="width:50px" />
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Book, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.Book.bookName)
            </div>
        </div>
        @using (Html.BeginForm("Delete", "Authors", new { id = Model.AuthorId }, FormMethod.Post))
        {
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to list", "Index")
</div>

BookPublishers/Views/Authors/Edit.cshtml
@model BookPublishers.ViewModel.AuthorEditModel
@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col-12">
        <h3>Add new Author</h3>

        @using (Html.BeginForm("Edit", "Authors", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.AuthorId)
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.AuthorName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.AuthorName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.AuthorName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.MobileNo, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.MobileNo, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.MobileNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.picture, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.picture, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BookId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.BookId, new SelectList(ViewBag.Book, "BookId", "bookName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.BookId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to list", "Index")
</div>
@section styles{

    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
   
}

BookPublishers/Views/Authors/Index.cshtml
@model IEnumerable<BookPublishers.Models.Author>
@{ ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h2>Authors</h2>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add new", "Create", "Authors", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.AuthorName)</th>

                    <th>@Html.DisplayNameFor(x => x.MobileNo)</th>
                    <th></th>
                    <th>@Html.DisplayNameFor(x => x.Book.bookName)</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var t in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => t.AuthorName)</td>
                        <td>@Html.DisplayFor(x => t.MobileNo)</td>
                        <td><img src="~/Assets/@t.picture" class="rounded-circle" style="width:50px" /></td>
                        <td>@Html.DisplayFor(x => t.Book.bookName)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Authors", new { id = t.AuthorId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Authors", new {id=t.AuthorId })" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>